[build-system]
requires = ["setuptools", "wheel", "git+https://github.com/scikit-build/scikit-build.git@master", "cython", "cmake", "ninja"]

[tool.black]
line-length = 109

[tool.isort]
profile = "black"
multi_line_output = 3
