[build-system]
requires = [
    "scikit-build-core",
    "cython>=3",
    "numpy>=2.0.0",
]
build-backend = "scikit_build_core.build"

[project]
name = "blosc2"
version = "3.0.0-beta.2.dev0"
description = "Python wrapper for the C-Blosc2 library"
readme = "README.rst"
authors = [{name = "Blosc Development Team", email = "blosc@blosc.org"}]
maintainers = [{ name = "Blosc Development Team", email = "blosc@blosc.org"}]
license = {text = "BSD-3-Clause"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.10"
# Follow guidlines from https://scientific-python.org/specs/spec-0000/
dependencies = [
    "numpy>=1.23.0",
    "ndindex",
    "msgpack",
    "numexpr",
    "py-cpuinfo",
    "httpx",
]
# Seems this is not supported by the current version of scikit-build-core
#dynamic = ["version"]


[project.optional-dependencies]
test = [
    "pytest",
    "psutil",
 ]

[project.urls]
homepage = "https://github.com/Blosc/python-blosc2"
documentation = "https://www.blosc.org/python-blosc2/python-blosc2.html"

[tool.cibuildwheel]
build-verbosity = 1
# Skip unsupported python versions as well as 32-bit platforms, which are not supported anymore.
skip = "*-manylinux_i686 cp*-win32 *_ppc64le *_s390x *musllinux*"
test-requires = "pytest psutil"
#test-command = "pytest -m 'not heavy' {project}/tests"
test-command = "pytest {project}/tests"
# Manylinux 2014 will be the default for x86_64 and aarch64
manylinux-x86_64-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"

[tool.ruff]
line-length = 109
extend-exclude = ["bench"]

[tool.ruff.lint]
extend-select = [
    "B",
    "I",
    "NPY",
    "PT",
    "RET",
    "SIM",
    "TCH",
    "UP",
]
ignore = [
    "PT006",
    "PT011",
    "RET505",
    "RET508",
    "SIM108",
]
