{% set name = "blosc2" %}
{% set version = "3.0.0rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/Blosc/python-blosc2/archive/refs/tags/v{{ version }}.tar.gz
  #url: https://github.com/Blosc/python-blosc2/archive/refs/tags/v3.0.0-rc2.tar.gz
  # sha256: cbf42b475c02145a979e4ac6cbd5ad9df49d23a417b56b6b7bdf5a9d0a4b0716
  url: /tmp/blosc2-3.0.0rc3.tar.gz
  sha256: 74c7c81cdbf28702fc751f3b6079b1e3653fec8fd285d54214e962c2113c593c
  include:
    - pyproject.toml

build:
  number: 0
  script_env:
    - USE_SYSTEM_BLOSC2=1
  script:
    #- {{ PYTHON }} -m pip install --no-deps --ignore-installed .
    #- -no-deps --no-build-isolation
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python >=3.11
    - pip
    - scikit-build-core
    - cython >=3
    - numpy >=2.0.0
    - c-blosc2 >=2.15.2
    - ninja
  host:
    - python >=3.11
    - pip
    - scikit-build-core
    - cython >=3
    - numpy >=2.0.0
  run:
    - python >=3.11
    - numpy >=1.25.0
    - ndindex
    - msgpack-python
    - numexpr
    - py-cpuinfo
    - httpx

test:
  imports:
    - blosc2
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v --pyargs blosc2

about:
  home: https://github.com/Blosc/python-blosc2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A flexible computational engine for the fast Blosc2 compression library
  description: |
    Blosc2 is a high-performance compressor optimized for binary data. It adds a flexible computational engine, making it ideal for scientific computing and other data-intensive applications.
  doc_url: https://www.blosc.org/python-blosc2
  dev_url: https://github.com/Blosc/python-blosc2

extra:
  recipe-maintainers:
    - FrancescAlted
