{% set name = "blosc2" %}  # TODO: should be python-blosc2 or blosc2 as in PyPI?
{% set version = "3.0.0rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # TODO: make actual tarballs work
  # url: https://github.com/Blosc/python-blosc2/archive/refs/tags/v{{ version }}.tar.gz
  url: /tmp/blosc2-3.0.0rc3.tar.gz
  sha256: ac822fd8d60e7356f48c638266b83486e31790fd70e482f814356be33f3fcedb
  include:
    - pyproject.toml

build:
  number: 0
  script_env:
    - USE_SYSTEM_BLOSC2=1
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python >=3.11
    - pip
    - scikit-build-core
    - cython >=3
    - numpy >=2.0.0
    - c-blosc2 >=2.15.2
    - ninja
  host:
    - python >=3.11
    - pip
    - scikit-build-core
    - cython >=3
    - numpy >=2.0.0
    - c-blosc2 >=2.15.2
  run:
    - python >=3.11
    - numpy >=1.25.0
    - c-blosc2 >=2.15.2
    - ndindex
    - msgpack-python
    - numexpr
    - py-cpuinfo
    - httpx

test:
  imports:
    - blosc2
  requires:
    - pip
    #- pytest
  commands:
    - pip check
    - python -c "import blosc2; print(blosc2.__version__)"
    - python -c "import blosc2; blosc2.print_versions()"
    # The test suite is not being installed
    #- pytest -v

about:
  home: https://github.com/Blosc/python-blosc2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A flexible computational engine for the fast Blosc2 compression library
  description: |
    Blosc2 is a high-performance compressor optimized for binary data. It adds a flexible computational engine, making it ideal for scientific computing and other data-intensive applications.
  doc_url: https://www.blosc.org/python-blosc2
  dev_url: https://github.com/Blosc/python-blosc2

extra:
  recipe-maintainers:
    - FrancescAlted
