name: macOS Python wheels
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - plugins
    tags:        
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build_wheels_macos:
    name: Build wheels on macos-latest
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        env:
          CIBW_BUILD: 'cp39-*'
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_BEFORE_BUILD: python -m pip install -r requirements.txt
          CIBW_BEFORE_TEST: python -m pip install -r requirements-tests.txt
          CIBW_TEST_COMMAND: python -m pytest {project}/tests
          CIBW_BUILD_VERBOSITY: 1
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
