name: Build and test blosc2 package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


defaults:
  run:
    shell: bash

jobs:
  build:
    name: On ${{ matrix.os }} using Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ 3.7, 3.8, 3.9 ]


    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install MSVC amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-tests.txt

      - name: Build package
        run: |
          python setup.py build_ext -j 4 --build-type=RelWithDebInfo

      - name: Lint with flake8
        run: |
          python -m pip install flake8
          flake8 blosc2 --count --exclude blosc2/c-blosc2/ --max-complexity 10 --max-line-length 110  --statistics

      - name: Test with pytest
        run: |
          PYTHONPATH=. pytest
